"""添加附件欄位到 work_experience 和 projects 表

Revision ID: ce10aaa23747
Revises: d711f173f9e3
Create Date: 2026-01-04 17:26:58.246721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce10aaa23747'
down_revision: Union[str, None] = 'd711f173f9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 原本的 ALTER COLUMN 操作 (已註解於 2026-01-04，原因：SQLite 不支援 ALTER COLUMN)
    # op.alter_column('project_details', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            autoincrement=True)
    # op.alter_column('project_details', 'created_at',
    #            existing_type=sa.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('project_details', 'updated_at',
    #            existing_type=sa.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.create_index(op.f('ix_project_details_id'), 'project_details', ['id'], unique=False)

    # 新增附件欄位 (修改於 2026-01-04，原因：只保留新增欄位的操作)
    op.add_column('projects', sa.Column('attachment_name', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('attachment_path', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('attachment_size', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('attachment_type', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('attachment_url', sa.String(length=500), nullable=True))
    op.add_column('work_experience', sa.Column('attachment_name', sa.String(length=255), nullable=True))
    op.add_column('work_experience', sa.Column('attachment_path', sa.String(length=500), nullable=True))
    op.add_column('work_experience', sa.Column('attachment_size', sa.Integer(), nullable=True))
    op.add_column('work_experience', sa.Column('attachment_type', sa.String(length=100), nullable=True))
    op.add_column('work_experience', sa.Column('attachment_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 刪除附件欄位 (修改於 2026-01-04，原因：只保留刪除欄位的操作)
    op.drop_column('work_experience', 'attachment_url')
    op.drop_column('work_experience', 'attachment_type')
    op.drop_column('work_experience', 'attachment_size')
    op.drop_column('work_experience', 'attachment_path')
    op.drop_column('work_experience', 'attachment_name')
    op.drop_column('projects', 'attachment_url')
    op.drop_column('projects', 'attachment_type')
    op.drop_column('projects', 'attachment_size')
    op.drop_column('projects', 'attachment_path')
    op.drop_column('projects', 'attachment_name')

    # 原本的 ALTER COLUMN 操作 (已註解於 2026-01-04，原因：SQLite 不支援 ALTER COLUMN)
    # op.drop_index(op.f('ix_project_details_id'), table_name='project_details')
    # op.alter_column('project_details', 'updated_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=sa.TIMESTAMP(),
    #            existing_nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('project_details', 'created_at',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=sa.TIMESTAMP(),
    #            existing_nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('project_details', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            autoincrement=True)
    # ### end Alembic commands ###
